diff a/Makefile b/Makefile	(rejected hunks)
@@ -2,7 +2,7 @@
 VERSION = 6
 PATCHLEVEL = 3
 SUBLEVEL = 8
-EXTRAVERSION =
+EXTRAVERSION = sandbpf0.2.0
 NAME = Hurr durr I'ma ninja sloth
 
 # *DOCUMENTATION*
